# =============================================================================
# GitHub Discussions - General Discussion Template
# =============================================================================
# Template for general discussions about QuranBot
# =============================================================================

body:
  - type: markdown
    attributes:
      value: |
        # 🕌 Welcome to QuranBot Discussions!

        Thank you for participating in our community discussions. This is a space for:
        - General questions about QuranBot
        - Sharing your experiences with the bot
        - Community support and help
        - Islamic knowledge discussions related to the bot's content

        Please be respectful and follow Islamic etiquette in all discussions.

  - type: textarea
    id: discussion-content
    attributes:
      label: "Discussion Topic"
      description: "Share your thoughts, questions, or experiences with QuranBot"
      placeholder: "What would you like to discuss about QuranBot?"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "What category best describes your discussion?"
      options:
        - General Support
        - Islamic Content Questions
        - Bot Features
        - Community
        - Technical Questions
        - Suggestions
        - Other
    validations:
      required: true

  - type: checkboxes
    id: guidelines
    attributes:
      label: "Community Guidelines"
      description: "Please confirm you understand our community guidelines"
      options:
        - label: "I will maintain Islamic etiquette and respect in discussions"
          required: true
        - label: "I understand this is a community-driven project"
          required: true
        - label: "I will be patient and respectful with other community members"
          required: true
